<div class="Admin-listing">
        <h2><a href="<?=buildUrl('addColor')?>">AJOUTER UNE COULEUR</a></h2>
    
        <table class="Admin-listing-table">
            <thead class="Admin-listing-head">
                <tr>
                    <th>Nom de la Marque</th>
                    <th>Editer</th>
                    <th>Supprimer</th>
                </tr>
            </thead>
            <tbody class="Admin-listing-body">
                <?php foreach($colors as $color):?>
                    <tr id='color-<?php $color['idCouleur']?>'>
                        <td><?= $color['libCouleur']?></td>
                        <td><a href="<?=buildUrl('editColor',['color_id' => $color['idCouleur']])?>"><i class="far fa-edit"></i></a></td>
                        <td><a class='Delete-button' data-target="color" href="<?=buildUrl('deleteColor',['color_id' => $color['idCouleur']])?>"><i class="fas fa-trash-alt"></i></a></td>
                    </tr>
                <?php endforeach ?>

            </tbody>
        </table>
    </div>
    