<nav class="Admin-nav">
    <a href="<?=buildUrl('adminModel')?>" class="Admin-nav-link">Modeles</a>
    <a href="<?=buildUrl('adminBrand')?>" class="Admin-nav-link">Marques</a>
    <a href="<?=buildUrl('adminCategory')?>" class="Admin-nav-link">Catégories</a>
    <a href="<?=buildUrl('adminArticle')?>" class="Admin-nav-link">Articles</a>
    <a href="<?=buildUrl('adminSize')?>" class="Admin-nav-link">Taille</a>
    <a href="<?=buildUrl('adminColor')?>" class="Admin-nav-link">Color</a>
</nav>