<section class="Account">
    <div class="Account-userInfo UserInfo">
        <h3 class = "UserInfo-firstname"><?=$session['firstname']?></h3>
        <h3 class = "UserInfo-lastname"><?=$session['lastname']?></h3>
        <h3 class = "UserInfo-email"><?=$session['email']?></h3>
    </div>
    <a href="#" class ="Account-setting"><i class="fas fa-cog"></i></a>
    <a href="#" class ="Account-basket"><i class="fas fa-shopping-basket"></i></a>
    <aside>
        <ul>
            <li>
                
            </li>
        </ul>
    </aside>
</section>