<section class="NewCollection">
        <div class="wrapper">
            <ul class="items">
                <li id="item1" class="item"></li>
                <li class="item"></li>
                <li class="item"></li>
                <li class="item"></li>
                <li class="item"></li>
                <li class="item"></li>
                <li class="item"></li>
                <li class="item"></li>
                <li class="item"></li>
                <li class="item"></li>
            </ul>
        </div>
</section>

<section class="HomeNav">
    <a class="HomeNav-link" id="Infosboutique" href="">Infos sur la boutique</a>
    <a class="HomeNav-link" id="Eshop" href="">E-shop</a>
</section>

<section class="ForYou">
    <h2 class="ForYou-title">Pourrait vous plaire</h2>
    <section class="NewCollection">
        <div class="wrapper">
            <ul class="items">
                <li id="item1" class="item"></li>
                <li class="item"></li>
                <li class="item"></li>
                <li class="item"></li>
                <li class="item"></li>
                <li class="item"></li>
                <li class="item"></li>
                <li class="item"></li>
                <li class="item"></li>
                <li class="item"></li>
            </ul>
        </div>
    </section>
</section>
