<form action="<?=buildUrl('editBrand',['brand_id' => $brandId]);?>" method="post" class="Form">
    <fieldset class="Form-fieldset">
        <legend>Modifer une Categorie</legend>
        <div class="form-field">
            <label for="brandName" class="Form-field-lib">Nom de la Catégorie</label><br>
            <input type="text" name="brandName" id="brandName" class="Form-field-input" value='<?=$brand?>'>
        </div>
        <div class="Form-submit">
             <input type="submit" value="Modifier" class="Form-button">
         </div> 
    </fieldset>
</form>
