<form action="<?=buildUrl('addArticle');?>" method="post" class="Form">
    <fieldset class="Form-fieldset">
        <legend class="Form-fieldset-title">Ajouter un article </legend>
        <div class="Form-field">
            <label for="articleModel" class="Form-field-lib">Model</label><br>
            <select id="articleModel" name="articleModel" required class="Form-field-select">
                <?php foreach ($models as $model): ?>
                    <option value="<?=$model['idModel'];?>" class="Form-field-option"><?=$model['libModel'];?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="Form-field">
            <label for="articleColor" class="Form-field-lib">Couleur</label><br>
            <select id="articleColor" name="articleColor" class="Form-field-select" required>
                <?php foreach ($colors as $color): ?>
                    <option value="<?=$color['idCouleur'];?>"><?=$color['libCouleur'];?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="Form-field">
            <label for="articleSize" class="Form-field-lib">Taille</label><br>
            <select id="articleSize" name="articleSize" class="Form-field-select" required>
                <?php foreach ($sizes as $size): ?>
                    <option value="<?=$size['idTaille'];?>"><?=$size['libTaille'];?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="Form-field">
            <label for="articleNombre" class="Form-field-lib">Nombre d'articles</label><br>
            <input type="number" name="articleNombre" id="articleNombre" min="1" max="30" step ='100' class="Form-field-input">
        </div>
        <div class="Form-submit">
             <input type="submit" value="Ajouter" class="Form-button">
         </div>    
    </fieldset>
</form>
<!-- ATTRIBUT ACTION ?? -->
