<form action="<?=buildUrl('addBrand');?>" method="post" class="Form">
    <fieldset class="Form-fieldset">
        <legend>Ajouter une Marque</legend>
        <div class="Form-field">
            <label for="brandName" class="Form-field-lib">Model</label><br>
            <input type="text" name="brandName" id="brandName" class="Form-field-input">
        </div>
        <div class="Form-submit">
             <input type="submit" value="Ajouter" class="Form-button">
         </div>     
    </fieldset>
</form>